### PR TITLE
Fix: Alias reference unlock in preExpandConfig

### LINKED ISSUE #1121: [Task]: Fix alias reference unlock not pre expanding
### Task description

The basic output is unlocked by an alias reference unlock and this doesn't seem to work with our pre expanding logic

`shimmer/transaction/0x02b8488d0cd5ff39d8ade27a73c11e85bbc46171e4479d60f194869d7ebdc7d1`

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

Add check for alias reference unlock in `preExpandConfig`
closes #1121 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

### CODE REVIEW

File: client/src/helpers/stardust/preExpandedConfig.ts [hunk 1]
```diff
@@ -90,6 +104,30 @@ export function getInputsPreExpandedConfig(inputs: IInput[], unlocks: Unlock[],
     return inputsPreExpandedConfig;
 }
 
+function getReferencedAddresses(
+    inputs: IInput[],
+    unlocks: Unlock[],
```
Comment (msarcev) [inline client/src/helpers/stardust/preExpandedConfig.ts:109]: Since we always just use one unlock inside this function, consider just passing an `unlock` instead of `unlocks` and `idx` in the function. (+ optionally rename function to `getReferencedAddressesFromUnlock`)

File: client/src/helpers/stardust/preExpandedConfig.ts [hunk 2]
```diff
@@ -90,6 +104,30 @@ export function getInputsPreExpandedConfig(inputs: IInput[], unlocks: Unlock[],
...
+    idx: number,
+    bech32Hrp: string,
+): { referencedStateControllerAddress: string; referencedAliasAddress: string } {
+    let referencedStateControllerAddress = "";
+    let referencedAliasAddress = "";
+    const unlock = unlocks[idx];
+    if (unlock.type === UnlockType.Alias) {
+        // get the referenced alias output
```
Comment (msarcev) [inline client/src/helpers/stardust/preExpandedConfig.ts:117]: Each comment can be merged into it's line by just naming the variable differently :D 
```
// get the referenced alias output
const referencedAliasInput = inputs[(unlock as AliasUnlock).reference];
```
to
```
const referencedAliasOutput = inputs[(unlock as AliasUnlock).reference];
```

**Review by msarcev — APPROVED** [review]
