### PR TITLE
fix: quick polishes

### LINKED ISSUE #1432: [Task]: Quick polishes
### Task description

- [ ] Slot feed links dont use `?tab=Txs`, that tab doesnt exist
- [ ] If there is no value to display, copy shouldnt be displayed (please check everywhere)
image

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

1. Avoid showing copy button on undefined values
2. Remove `?tab=Txs` from slot link
3. Avoid breaking into two lines in the block page too

Fixes #1432 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: client/src/helpers/nova/hooks/useGenerateSlotsTable.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ function getSlotCommitmentTableRow(
                 tableData = {
                     type: TableCellType.Stats,
                     data: slotIndex.toString(),
-                    href: `/${network}/slot/${slotIndex}?tab=Txs`,
+                    href: `/${network}/slot/${slotIndex}`,
```
Comment (begonaalvarezd) [inline client/src/helpers/nova/hooks/useGenerateSlotsTable.ts:143]: the line above with `?tab=RefBlocks` should also be removed, there are no tabs in the slot page

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
mini comment

**Review by begonaalvarezd — APPROVED** [review]
