### PR TITLE
fix: nova visualizer not loading when switching networks

### LINKED ISSUE #1299: [Task]: Fix nova visualizer not loading when switching networks
### Task description

Fix nova visualizer not loading when switching networks
When you eg come from mainnet visualizer and change network to alphanet, the nova visualizer doesnt load

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

Get new blocks after switching to another network and switch back.
Closes #1299

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

1. Open `nova` visualizer
2. Switch no another network
3. Switch back.

Expected result: visualizer show new blocks

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: client/src/features/visualizer-vivagraph/store/tangle.ts [hunk 1]
```diff
@@ -37,6 +39,13 @@ export const useTangleStore = create<TangleState>()(
     devtools((set, get) => ({
         ...INITIAL_STATE,
 
+        resetTangleStore: () => {
+            set(() => {
+                return {
+                    ...INITIAL_STATE,
+                };
+            });
+        },
```
Comment (VmMad) [inline client/src/features/visualizer-vivagraph/store/tangle.ts:48]: This is not really what you expect, because at the start, when creating the store you are actually passing the reference to the Map stored in the INITIAL_STATE, so instead just manually copy the INITIAL_STATE so it doesn't use references to previous maps. You can actually check this by setting a console log in like this:

```typescript
        resetTangleStore: () => {
            set(() => {
                return {
                    ...INITIAL_STATE,
                };
            });
            console.log("after cleanup", get().blockIdToMetadata);
        },
```

Comment (VmMad) [reply client/src/features/visualizer-vivagraph/store/tangle.ts:48]:
```suggestion
        resetTangleStore: () => {
            set(() => {
                return {
                        blockIdToMetadata: new Map(),
                        visibleBlocks: [],
                        selectedNode: null,
                        search: "",
                };
            });
        },
```

**Review by VmMad — CHANGES_REQUESTED** [review]
It works now! Just one small change

**Review by VmMad — APPROVED** [review]
Perfect!

**Review by begonaalvarezd — APPROVED** [review]
