### PR TITLE
Fix: Improve Milestone Feed consistency

### LINKED ISSUE #848: [Bug]: Milestone stats unreliable on Shimmer/Testnet
### Issue description

* The milestone stats seam to have a lot of "misses" on Shimmer compared to Mainnet
image

* The last milestone seconds counter seams broken on Shimmer (possibly consequence of first point)
image

Investigate and fix!

### Expected behaviour

N/A

### Actual behaviour

N/A

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

_No response_

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

fixes #848

- when milestone feed don't get analytic value from cache - request it from db
- when switch between network - reset timer for latest milestone

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: api/src/services/stardust/influx/influxQueries.ts [hunk 1]
```diff
@@ -335,4 +335,15 @@ export const MILESTONE_STATS_QUERY = `
         last("no_payload_count") AS "noPayload"
     FROM "stardust_block_activity"
 `;
+export const MILESTONE_STATS_QUERY_BY_INDEX = `
+    SELECT
+        last("milestone_index") AS "milestoneIndex",
```
Comment (msarcev) [inline api/src/services/stardust/influx/influxQueries.ts:340]: I don't think the `last` part makes sense here. `last` is from the other query where we specifically need the "latest row" in the database (it's sorted by time by default in influx). Here we are looking for a specific milestone, maybe the query works but i'm concerned that it might not return the right data.
I would remove the `last` and just check the query works without it.

File: api/src/services/stardust/influx/influxDbClient.ts [hunk 2]
```diff
@@ -349,60 +375,56 @@ export abstract class InfluxDbClient {
...
+        }
+    }
 
-                    if (this._milestoneCache.size > MILESTONE_CACHE_MAX) {
-                        let lowestIndex: number;
-                        for (const index of this._milestoneCache.keys()) {
-                            if (!lowestIndex) {
-                                lowestIndex = index;
-                            }
+    private updateCacheMilestone(update: MilestoneUpdate) {
```
Comment (msarcev) [inline api/src/services/stardust/influx/influxDbClient.ts:388]: Small thing but i like `updateMilestoneCache` better.

**Review by msarcev — CHANGES_REQUESTED** [review]
